# Тема “Обучение с учителем”

## Задание 1
Импортируйте библиотеки pandas и numpy.   

Загрузите "Boston House Prices dataset" из встроенных наборов данных библиотеки sklearn..  

Разбейте эти датафреймы на тренировочные (X_train, y_train) и тестовые (X_test, y_test) с помощью функции train_test_split так, чтобы размер тестовой выборки
составлял 30% от всех данных, при этом аргумент random state должен быть равен 42.  

Создайте модель линейной регрессии под названием lr с помощью класса LinearRegression из модуля sklearn.linear_model.

Обучите модель на тренировочных данных (используйте все признаки) и сделайте предсказание на тестовых.

In [1]:
# Импортируем необходимые библиотеки
import pandas as pd
import numpy as np
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Загрузим данные
boston = load_boston()
X = pd.DataFrame(boston.data, columns=boston.feature_names)
y = pd.Series(boston.target)

# Разделим данные на тренировочные и тестовые выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Создадим модель линейной регрессии
lr = LinearRegression()

# Обучим модель на тренировочных данных
lr.fit(X_train, y_train)

# Сделаем предсказание на тестовых данных
y_pred = lr.predict(X_test)

# Выведем метрики
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))


ImportError: 
`load_boston` has been removed from scikit-learn since version 1.2.

The Boston housing prices dataset has an ethical problem: as
investigated in [1], the authors of this dataset engineered a
non-invertible variable "B" assuming that racial self-segregation had a
positive impact on house prices [2]. Furthermore the goal of the
research that led to the creation of this dataset was to study the
impact of air quality but it did not give adequate demonstration of the
validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of
this dataset unless the purpose of the code is to study and educate
about ethical issues in data science and machine learning.

In this special case, you can fetch the dataset from the original
source::

    import pandas as pd
    import numpy as np

    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]

Alternative datasets include the California housing dataset and the
Ames housing dataset. You can load the datasets as follows::

    from sklearn.datasets import fetch_california_housing
    housing = fetch_california_housing()

for the California housing dataset and::

    from sklearn.datasets import fetch_openml
    housing = fetch_openml(name="house_prices", as_frame=True)

for the Ames housing dataset.

[1] M Carlisle.
"Racist data destruction?"
<https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8>

[2] Harrison Jr, David, and Daniel L. Rubinfeld.
"Hedonic housing prices and the demand for clean air."
Journal of environmental economics and management 5.1 (1978): 81-102.
<https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>


Поскольку набор данных "Boston House Prices" был удален из библиотеки scikit-learn из-за этических проблем, мы будем использовать альтернативный набор данных "California Housing dataset", который можно загрузить с помощью функции fetch_california_housing из sklearn.datasets.

In [2]:
# Импортируем необходимые библиотеки
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Загрузим данные
california = fetch_california_housing()
X = pd.DataFrame(california.data, columns=california.feature_names)
y = pd.Series(california.target)

# Разделим данные на тренировочные и тестовые выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Создадим модель линейной регрессии
lr = LinearRegression()

# Обучим модель на тренировочных данных
lr.fit(X_train, y_train)

# Сделаем предсказание на тестовых данных
y_pred = lr.predict(X_test)

# Выведем метрики
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))


Mean Squared Error: 0.5305677824766758


## Задание 2
Создайте модель под названием model с помощью класса RandomForestRegressor из модуля sklearn.ensemble.  

Сделайте агрумент n_estimators равным 1000, max_depth должен быть равен 12 и random_state сделайте равным 42.  

Обучите модель на тренировочных данных аналогично тому, как вы обучали модель LinearRegression, но при этом в метод fit вместо датафрейма y_train поставьте y_train.values[:, 0], чтобы получить из датафрейма одномерный массив Numpy,
так как для класса RandomForestRegressor в данном методе для аргумента y предпочтительно применение массивов вместо датафрейма.  

Сделайте предсказание на тестовых данных и посчитайте R2. Сравните с результатом из предыдущего задания.  

Напишите в комментариях к коду, какая модель в данном случае работает лучше.

In [3]:
# Импортируем необходимые библиотеки
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Загрузим данные
california = fetch_california_housing()
X = pd.DataFrame(california.data, columns=california.feature_names)
y = pd.Series(california.target)

# Разделим данные на тренировочные и тестовые выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Создадим и обучим модель линейной регрессии
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)
mse_lr = mean_squared_error(y_test, y_pred_lr)
r2_lr = r2_score(y_test, y_pred_lr)

# Создадим модель RandomForestRegressor
model = RandomForestRegressor(n_estimators=1000, max_depth=12, random_state=42)

# Обучим модель на тренировочных данных
model.fit(X_train, y_train.values)

# Сделаем предсказание на тестовых данных
y_pred_rf = model.predict(X_test)

# Вычислим метрики
mse_rf = mean_squared_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

# Выведем результаты
print(f"Linear Regression - Mean Squared Error: {mse_lr}, R2: {r2_lr}")
print(f"Random Forest Regressor - Mean Squared Error: {mse_rf}, R2: {r2_rf}")

# Сравнение моделей
# Random Forest Regressor работает лучше, если R2 выше и MSE ниже
if r2_rf > r2_lr:
    print("Random Forest Regressor работает лучше.")
else:
    print("Linear Regression работает лучше.")


Linear Regression - Mean Squared Error: 0.5305677824766758, R2: 0.595770232606166
Random Forest Regressor - Mean Squared Error: 0.26971891519368185, R2: 0.7945061536878142
Random Forest Regressor работает лучше.


## *Задание 3
Вызовите документацию для класса RandomForestRegressor, найдите информацию об атрибуте feature_importances_.  

С помощью этого атрибута найдите сумму всех показателей важности, установите, какие два признака показывают наибольшую важность.

In [4]:
# Получим важности признаков
feature_importances = model.feature_importances_

# Найдем сумму всех показателей важности
total_importance = np.sum(feature_importances)
print(f"Сумма всех показателей важности: {total_importance}")

# Найдем два признака с наибольшей важностью
feature_names = X.columns
importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': feature_importances})
top_features = importance_df.sort_values(by='Importance', ascending=False).head(2)
print("Два признака с наибольшей важностью:")
print(top_features)

Сумма всех показателей важности: 0.9999999999999999
Два признака с наибольшей важностью:
    Feature  Importance
0    MedInc    0.559269
5  AveOccup    0.139126


## *Задание 4
В этом задании мы будем работать с датасетом, с которым мы уже знакомы по домашнему заданию по библиотеке Matplotlib, это датасет Credit Card Fraud Detection.Для этого датасета мы будем решать задачу классификации - будем определять,какие из транзакции по кредитной карте являются мошенническими.Данный датасет сильно несбалансирован (так как случаи мошенничества
относительно редки),так что применение метрики accuracy не принесет пользы и не поможет выбрать лучшую модель.Мы будем вычислять AUC, то есть площадь под кривой ROC.

Импортируйте из соответствующих модулей RandomForestClassifier, GridSearchCV и train_test_split.  

Загрузите датасет creditcard.csv и создайте датафрейм df.  

С помощью метода value_counts с аргументом normalize=True убедитесь в том, что выборка несбалансирована. Используя метод info, проверьте, все ли столбцы содержат числовые данные и нет ли в них пропусков.Примените следующую настройку, чтобы можно было просматривать все столбцы датафрейма:
pd.options.display.max_columns = 100.  

Просмотрите первые 10 строк датафрейма df.  

Создайте датафрейм X из датафрейма df, исключив столбец Class.  

Создайте объект Series под названием y из столбца Class.  

Разбейте X и y на тренировочный и тестовый наборы данных при помощи функции train_test_split, используя аргументы: test_size=0.3, random_state=100, stratify=y.  
У вас должны получиться объекты X_train, X_test, y_train и y_test.  
Просмотрите информацию о их форме.  

Для поиска по сетке параметров задайте такие параметры:
parameters = [{'n_estimators': [10, 15],
'max_features': np.arange(3, 5),
'max_depth': np.arange(4, 7)}]  

Создайте модель GridSearchCV со следующими аргументами:  
estimator=RandomForestClassifier(random_state=100), param_grid=parameters,  
scoring='roc_auc', cv=3.  

Обучите модель на тренировочном наборе данных (может занять несколько минут).  

Просмотрите параметры лучшей модели с помощью атрибута best_params_.  

Предскажите вероятности классов с помощью полученной модели и метода predict_proba.  

Из полученного результата (массив Numpy) выберите столбец с индексом 1 (вероятность класса 1) и запишите в массив y_pred_proba. Из модуля sklearn.metrics импортируйте метрику roc_auc_score.  

Вычислите AUC на тестовых данных и сравните с результатом,полученным на тренировочных данных, используя в качестве аргументов массивы y_test и y_pred_proba.

In [5]:
# Импортируем необходимые библиотеки
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import roc_auc_score

# Загрузим датасет
df = pd.read_csv('/content/drive/MyDrive/creditcard.csv')

# Убедимся в том, что выборка несбалансирована
print(df['Class'].value_counts(normalize=True))

# Проверим, все ли столбцы содержат числовые данные и нет ли в них пропусков
print(df.info())

# Настроим отображение всех столбцов
pd.options.display.max_columns = 100

# Просмотрим первые 10 строк датафрейма
print(df.head(10))

# Создадим датафрейм X из df, исключив столбец Class
X = df.drop('Class', axis=1)

# Создадим объект Series y из столбца Class
y = df['Class']

# Разделим данные на тренировочные и тестовые наборы
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100, stratify=y)

# Просмотрим информацию о форме данных
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

# Зададим параметры для поиска по сетке
parameters = [{'n_estimators': [10, 15],
               'max_features': np.arange(3, 5),
               'max_depth': np.arange(4, 7)}]

# Создадим модель GridSearchCV
grid_search = GridSearchCV(estimator=RandomForestClassifier(random_state=100),
                           param_grid=parameters,
                           scoring='roc_auc',
                           cv=3)

# Обучим модель на тренировочном наборе данных
grid_search.fit(X_train, y_train)

# Просмотрим параметры лучшей модели
print(grid_search.best_params_)

# Предскажем вероятности классов
y_pred_proba = grid_search.predict_proba(X_test)[:, 1]

# Вычислим AUC на тестовых данных
auc_score = roc_auc_score(y_test, y_pred_proba)
print(f'AUC на тестовых данных: {auc_score}')

# Для сравнения вычислим AUC на тренировочных данных
y_train_pred_proba = grid_search.predict_proba(X_train)[:, 1]
train_auc_score = roc_auc_score(y_train, y_train_pred_proba)
print(f'AUC на тренировочных данных: {train_auc_score}')


Class
0    0.998273
1    0.001727
Name: proportion, dtype: float64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-

## *Дополнительные задания:
1). Загрузите датасет Wine из встроенных датасетов sklearn.datasets с помощью функции load_wine в переменную data.

2). Полученный датасет не является датафреймом. Это структура данных, имеющая ключи аналогично словарю. Просмотрите тип данных этой структуры данных и создайте список data_keys, содержащий ее ключи.  

3). Просмотрите данные, описание и названия признаков в датасете. Описание нужно вывести в виде привычного, аккуратно оформленного текста, без обозначений переноса строки, но с самими переносами и т.д.

In [6]:
# Импортируем необходимые библиотеки
from sklearn.datasets import load_wine

# 1. Загрузите датасет Wine
data = load_wine()

# 2. Просмотрите тип данных и создайте список data_keys
print(type(data))  # Тип данных
data_keys = list(data.keys())  # Ключи структуры данных
print(data_keys)

# 3. Просмотрите данные, описание и названия признаков
# Данные
print(data.data)

# Описание
description = data.DESCR
print(description)

# Названия признаков
feature_names = data.feature_names
print(feature_names)

# Оформленное описание
formatted_description = """
The Wine dataset is a classic and very easy multi-class classification dataset.
It contains 178 samples of wines grown in the same region in Italy but derived from three different cultivars.

**Features**:
{}
**Target**:
- Class 0: {}
- Class 1: {}
- Class 2: {}

Description:
{}
""".format(", ".join(feature_names), data.target_names[0], data.target_names[1], data.target_names[2], description)

print(formatted_description)


<class 'sklearn.utils._bunch.Bunch'>
['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names']
[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
   